### ISSUE TITLE
Formato del título de la PR

### ISSUE THREAD

**Issue by lombervid** [mouredev/retos-programacion-2023#11]
Hola.

Una cosa que no me termina de quedar claro es si ¿hay algún formato a seguir para el título de las PRs?

Por ejemplo, la primera la mandé con formato: `Reto #[NÚMERO-RETO]/[LENGUAJE-UTILIZADO]/[USUARIO].[EXTENSIÓN]`, ya que por está parte me hizo pensar que ese debía de ser el formato del título:

>Por ejemplo, si has resuelto el reto #0 utilizando el lenguaje de programación Kotlin y tu usuario de GitHub se llama mouredev, tu corrección deberá estar en **"Retos/Reto #0/kotlin/mouredev.kt”**. **Se rechazarán las Pull Request que no sigan este formato**.

Pero en esta última que hice ya me salía por defecto un formato `Solución Reto #[NÚMERO-RETO] [LENGUAJE-UTILIZADO]`

Entonces, ¿este último es el formato que se debe de seguir?, ¿hay algún otro formato?, o ¿no importa el formato del título?

Un saludo.

**Comment by titoworlddev** [comment]
Yo tambien estaba en duda con eso, pero creo que el titulo de las PR da igual puedes usar el que te pone por defecto, pero lo importante es que tu solucion la pongas con la ruta correcta que se explica en la web
```
NOTA: Cuando realices una Pull Request para aportar tu solución al ejercicio sigue esta convención: “Retos/[directorio_reto]/[lenguaje_utilizado]/[usuario_github.extension]" (Ej: Retos/Reto #0/kotlin/mouredev.kt)
```
Creo que es asi, pero bueno sino que nos lo deje claro Moure.

**Comment by lombervid** [comment]
Sí, eso es lo que al final entiendo también.

Aunque, en mi opinión, creo que sería mejor si se especificara un formato para el título de las PRs. Creo que se vería un poco más organizado. Por ejemplo, si ves ahora la sección de PRs y ves cada quien con su formato de título.

**Comment by titoworlddev** [comment]
Pues si, toda la razon, se veria mucho mas limpio, pero bueno de momento lo importante es la estructura. Mientras Moure no diga lo contrario pues habra todo tipo de titulos xD

**Comment by lombervid** [comment]
Creo que algo como esto, por ejemplo:
![image](https://user-images.githubusercontent.com/3432651/209584856-77ac36ce-9ab2-49b0-8103-f6f488dbab89.png)

Se vería mejor que esto:
![image](https://user-images.githubusercontent.com/3432651/209584876-9346e43f-f169-4625-8dde-bde5a95248ae.png)

Igual tal vez incluir el usuario también.

**Comment by Arian1192** [comment]
Comparto tu opinión @lombervid  si mantenemos una convención sera mas fácil a la hora de "husmear" otras alternativas o lenguajes.

**Comment by Arian1192** [comment]
si no quizás seguir la convención de Reto #[Numero del reto] [Lenguaje] , al final abajo en la PR ya pone el usuario.

**Comment by titoworlddev** [comment]
Bueno yo estoy de acuerdo tambien, podemos hacerlo nosotros asi y a ver si el resto de la gente lo coge como buena practica.

**Comment by Pratchetman** [comment]
Es mi primera vez en GitHub y no veo como modificar eso que comentáis. En mi fork si que tengo el archivo JS metido en un Path tal y como pide mouredev, pero al lanzar la PR me lo coloca tal cual, solo nombre de archivo.

Funcionalidades no faltaran, pero de "intuitivo" no va sobrado esto que digamos.

Saludos!,

**Comment by lombervid** [comment]
> Es mi primera vez en GitHub y no veo como modificar eso que comentáis. En mi fork si que tengo el archivo JS metido en un Path tal y como pide mouredev, pero al lanzar la PR me lo coloca tal cual, solo nombre de archivo.
> 
> Funcionalidades no faltaran, pero de "intuitivo" no va sobrado esto que digamos.
> 
> Saludos!,

Cuando le das crear la PR, ahí puedes cambiar el título a cómo tú lo quieras (te pone uno por defecto pero puedes cambiarlo).

También, una vez creado, puedes:

1. Ir a [la lista de PRs](https://github.com/mouredev/retos-programacion-2023/pulls), buscar el tuyo y entrar a la descripción.
2. Presionar el botón `Edit` de arriba a la derecha
![image](https://user-images.githubusercontent.com/3432651/209694354-a33f84b2-f54c-45b3-8457-26929fff6e5f.png)
3. Te saldrá un input con el título actual donde puedes modificarlo
4. Presionas `Save`
![image](https://user-images.githubusercontent.com/3432651/209694485-5cfc0545-939c-4e2e-8199-5827302aa833.png)

Ya con eso se debría de haber actualizado el título

**Comment by Pratchetman** [comment]
Oye, pues mil gracias por la ayuda!!.

Saludos!;

**Comment by mouredev** [comment]
Hola a todo el mundo.

No he establecido un formato para el título de la PR. Creo que sería suficiente con el número del reto y el lenguaje. De todas formas es algo que podría definir para el segundo reto. Muchas gracias por todo.
