### ISSUE TITLE
Conflicto pull request

### ISSUE THREAD

**Issue by davidleonmayor** [mouredev/retos-programacion-2023#5632]
# Contexto 
Compete el primer ejercicio con mi solución y realicé un commit sin problemas. Luego realice el segundo ejercicio "Reto #1 - EL LENGUAJE HACKER [Fácil]"  y agregue mis cambios en un commit.

Antes de hacerlo  realice un "git pull", me dio un alerta. y para solucionarlo ejecute un " git config pull.rebase false" y finalmente subí mi cambio. 

Al revisar el nuevo cambio, se unió el primer y el segundo commit y no un commit separado por cada reto como lo esperaba. Entonces decidi quitar mi ultimo cambio y subirlo nuevamente fracmento por gracmente con un "git reset HEAD~"
pero al parecer elimine un commit que no es mio.

fuentes: https://stackoverflow.com/questions/6217156/break-a-previous-commit-into-multiple-commits
commit: #5630

**Comment by Roswell468** [comment]
Hola! No vimos ningún conflicto en tu PR.
Incluía tus dos soluciones y nada más. 
Saludos!
